export const FILM_TRIVIA = [
  "Pedro Pascal got his big break starring in a surreal commercial for Denny’s Sausages.",
  "Ayo Edebiri spent 3 years speaking in an \"Elvis voice\" and needed a dialect coach to stop.",
  "Florence Pugh started her career as a backup dancer for Selena Gomez in a Sears commercial.",
  "Timothée Chalamet is a highly skilled amateur boxer who trains in between film sets.",
  "Mia Goth used to perform \"autopsies\" on dead lizards she found in her backyard as a kid.",
  "Jacob Elordi turned down a record deal for his rock band \"The Sons of Mr. Green Genes.\"",
  "Anya Taylor-Joy decided to become an actress because she wanted to play an Ewok in Star Wars.",
  "Paul Mescal was a classically trained professional dancer in jazz and ballet before acting.",
  "Zendaya attended nine different schools in a single year while moving across three countries.",
  "Barry Keoghan was working at a legal marijuana dispensary when he got the call for Short Term 12.",
  "Greta Lee refused to play any Nazi characters for years until she read the script for The Zone of Interest.",
  "Charles Melton is a 1st dan black belt in Taekwondo and competed in the World Championships.",
  "Austin Butler is an obsessive ceramicist and often spends his time between takes making pottery.",
  "Rachel Zegler was a high-profile plaintiff in a lawsuit against North Carolina’s \"bathroom bill.\"",
  "Cillian Murphy was a professional street performer and contemporary dancer before his breakout.",
  "Jenna Ortega made a PowerPoint presentation called \"Project Hollywood\" to convince her parents to move to LA.",
  "Ayo Edebiri is a classically trained opera singer who graduated from the Yale School of Drama.",
  "Jeremy Allen White was a professional gymnast and dancer for a decade before he ever tried acting.",
  "Mia Goth once claimed she lived off money she made as a professional gambler on horse races.",
  "Jacob Elordi had a high school rap persona named \"Lil Timmy Tim\" and made songs about statistics.",
  "Zendaya co-hosted a cult-favorite podcast called Iconography where guests discussed their \"icons.\"",
  "Paul Mescal almost joined the Royal Marines before his acting career took off.",
  "Florence Pugh worked in a steakhouse and a jewelry shop to support herself before her breakout.",
  "Timothée Chalamet was a student at the actual boarding school where his film was being filmed when cast.",
  "Sandra Hüller insists on wearing her own grandmother’s antique jewelry in her films to feel \"grounded.\"",
  "Barry Keoghan despite his tough-guy roles, struggled for years to learn how to drive a car.",
  "Austin Butler famously lied about attending the Royal Academy of Dramatic Art (RADA) to get early jobs.",
  "Ayo Edebiri made her professional debut in the Broadway musical The 25th Annual Putnam County Spelling Bee.",
  "Jacob Elordi was a star defensive back for the Kansas State University football team.",
  "Mia Goth was a professional ballerina with the American Ballet Theatre before turning to acting.",
  "Ayo Edebiri was a high-level competitive fencer and was once ranked 3rd in the state of California.",
  "Jacob Elordi played professional basketball in the Greek B League before becoming a filmmaker.",
  "Hunter Schafer once directed a two-night live-streamed production of Chekhov’s The Seagull entirely within the video game The Sims 4.",
  "Yorgos Lanthimos directed the iconic \"Virtual Insanity\" music video for Jamiroquai, which won an MTV Video Music Award.",
  "Celine Song is only the third woman in history to win the Palme d'Or at the Cannes Film Festival.",
  "Florence Pugh was college roommates with Kate McKinnon and the two used to perform \"strange musicals\" together.",
  "Greta Gerwig based her film Past Lives on the real moment she had to translate between her husband and her childhood sweetheart in a bar.",
  "Cillian Murphy spent five months in a religious boarding school in Israel during his childhood.",
  "Jenna Ortega is a massive fan of musical theater and knows every word to the musicals Cats and Starlight Express.",
  "Jonathan Glazer' upcoming movie Bugonia is a remake of the South Korean science fiction cult classic Save the Green Planet!.",
  "Greta Lee started her career making documentary films about social justice and youth protests in France.",
  "Anya Taylor-Joy originally studied clinical psychology before pivoting to playwriting and eventually cinema.",
  "Yorgos Lanthimos directed music videos for Massive Attack and Radiohead before making his feature film debut.",
  "Ayo Edebiri was rejected from every playwriting MFA program she applied to before finding success in acting.",
  "Celine Song became the first female French filmmaker to ever win an Academy Award for Best Original Screenplay.",
  "Greta Lee’s father is a legend in South Korean cinema who gave early career breaks to actors like Song Kang-ho.",
  "Jonathan Glazer was denied permission by the Greek government to film the ending of his movie at the Acropolis.",
  "Justine Triet is known for using hidden camera systems to capture naturalistic, un-staged performances on set.",
  "Sofia Coppola was the first female American director to serve as the Jury President at the Cannes Film Festival.",
  "Yorgos Lanthimos is currently developing a high-stakes esports drama series for HBO titled Damage.",
  "Sandra Hüller is a prominent member of the French gender equality group Collectif 50/50.",
  "Jonathan Glazer worked as a director of television commercials for years before making his first feature film.",
  "David Lynch moved to China for a year at age 10 because his mother was a lecturer at Nanjing University.",
  "Sofia Coppola recorded her first ever song, titled \"Green Eggs and Ham,\" in a basement studio at age 13.",
  "David Lynch used a random bear mascot found at a school for a famous project cover because it was just \"there\" during the shoot.",
  "Sofia Coppola never wrote down her creative ideas or lyrics, preferring to record herself on video to remember them.",
  "David Lynch sourced the majority of the background samples for his debut from a crate of records gifted by his girlfriend’s father.",
  "Sofia Coppola once told her high school gym teacher that she was going to be the best artist in the entire world.",
  "David Lynch stood in front of a mirror as a teenager and told his mother, \"Look at me, I could be a teenage sex symbol.\"",
  "Sofia Coppola dropped out of university after just one year to pursue a career in the arts full-time.",
];
